name: Run build project

on:
  push:
jobs:
  build-gradle-project:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload BSTrees jar
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: BSTrees lib
          path: BSTrees/build/libs/BSTrees.jar

      - if: matrix.os == 'ubuntu-latest'
        name: Run Test Coverage
        run: ./gradlew jacocoTestReport

      - if: matrix.os == 'ubuntu-latest'
        name: Jacoco Code Coverage Report
        uses: cicirello/jacoco-badge-generator@v2.8.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: BSTrees/build/jacoco/jacocoCsv